100-intel

diff --git a/0x00-hello_world/100-intel b/0x00-hello_world/100-intel
--- a/0x00-hello_world/100-intel
+++ b/0x00-hello_world/100-intel
@@ -1,2 +1,6 @@
 #!/bin/bash
-gcc -S -masm=intel $CFILE
+if [ -z "$CFILE" ]; then
+    echo "Error: Provide the C file name in the CFILE variable."
+    exit 1
+BASENAME=$(basename "$CFILE" .c)
+gcc -S -masm=intel "$CFILE" -o "$BASENAME.s"
